import {useEffect,useRef,useState} from 'react';
import {ArrowUp,BookOpen,Database,History,MessageSquare,Mic,MicOff,Plus,Settings,ShieldCheck,X,ChevronRight,Factory,Search,Volume2} from 'lucide-react';
import {api,readStored,saveStored,type Document,type Evidence,type Message,type Workspace} from './types';
import {useRealtimeVoice} from './hooks/useRealtimeVoice';

const welcome:Message={role:'assistant',text:'작업의 흐름을 함께 확인해요.\n작업지시를 선택하고 공정 진행, 검사 결과, 금형 상태를 물어보세요.'};
const labels:Record<string,string>={active_work_orders:'진행 작업',press_alerts:'설비 주의',maintenance_risks:'정비 검토',incoming_holds:'입고 검토',shipment_pending:'출하 대기'};
const fieldLabels:Record<string,string>={work_order:'작업지시',material_lot:'소재 LOT',press_id:'프레스',die_id:'금형',item_name:'품명',item_code:'품번',quantity:'수량 (개)',order_qty:'지시 수량 (개)',due_date:'납기',current_process:'현재 공정',progress_pct:'진행률 (%)',measured_at:'측정 시각',pressure_mpa:'압력 (MPa)',die_temperature_c:'금형 온도 (°C)',vibration_mm_s:'진동 (mm/s)',current_a:'전류 (A)',stroke_spm:'스트로크 (spm)',status:'상태',result:'결과',final_result:'최종 결과',risk_score:'위험점수 (미검증)',risk_level:'위험등급',nominal_remaining_strokes:'명목 잔여 스트로크',rated_strokes:'정격 스트로크',accumulated_strokes:'누적 스트로크',usage_pct:'사용률 (%)'};
function DataView({data}:{data:unknown}){
 if(Array.isArray(data))return data.length?<div className="records">{data.map((row,i)=><DataView key={i} data={row}/>)}</div>:<p className="muted">해당 기록 없음 · 미확인</p>;
 if(data&&typeof data==='object')return <dl className="record">{Object.entries(data).map(([key,value])=><div key={key}><dt>{fieldLabels[key]||key}</dt><dd>{typeof value==='object'&&value!==null?<DataView data={value}/>:String(value??'미확인')}</dd></div>)}</dl>;
 return <span>{String(data??'미확인')}</span>;
}
function EvidenceView({items,openDoc}:{items:Evidence[];openDoc:(id:string)=>void}){return <div className="evidence">{items.map((e,i)=><details key={i}><summary><ShieldCheck size={14}/>{e.title}<span>근거 보기</span></summary><small>{e.source} · {e.approval_status} {e.queried_at&&`· 조회 ${new Date(e.queried_at).toLocaleString('ko-KR')}`}</small>{e.kind==='document'?<><p className="pre">{e.text}</p>{e.document_id&&<button onClick={()=>openDoc(e.document_id!)}>원문 열기</button>}</>:<DataView data={e.records}/>}</details>)}</div>}
export default function App(){
 const [workspace,setWorkspace]=useState<Workspace>(),[error,setError]=useState(''),[lot,setLot]=useState(''),[mode,setMode]=useState<'demo'|'ai'>('demo');
 const [messages,setMessages]=useState<Message[]>([welcome]),[question,setQuestion]=useState(''),[busy,setBusy]=useState(false);
 const [history,setHistory]=useState<{question:string;lot:string}[]>(()=>{const h=readStored<unknown>('kwp-history',[]);return Array.isArray(h)?h.filter(x=>typeof x?.question==='string'&&typeof x?.lot==='string').slice(0,20):[]});
 const [token,setToken]=useState(()=>readStored<string>('kwp-access','')),[settings,setSettings]=useState(false),[panel,setPanel]=useState<'data'|'questions'|null>(null);
 const [resource,setResource]=useState<'docs'|'tables'>('docs'),[search,setSearch]=useState(''),[documents,setDocuments]=useState<Document[]>([]),[table,setTable]=useState('work_orders'),[offset,setOffset]=useState(0),[rows,setRows]=useState<unknown[]>([]),[dataError,setDataError]=useState('');
 const [doc,setDoc]=useState<Document|null>(null),[group,setGroup]=useState('생산·품질');
 const epoch=useRef(0),pending=useRef<AbortController|null>(null),end=useRef<HTMLDivElement>(null),dialog=useRef<HTMLDialogElement>(null),docEpoch=useRef(0);
 const voice=useRealtimeVoice(token,lot,turn=>setMessages(m=>[...m,{...turn,mode:'voice'}]), evidence=>setMessages(m=>[...m,{role:'assistant',text:'음성 대화에서 조회한 원본 근거입니다.',evidence,mode:'voice'}]));
 useEffect(()=>{api<Workspace>('/api/workspace').then(setWorkspace).catch(e=>setError(e.message))},[]);
 useEffect(()=>{const controller=new AbortController();setDataError('');setDocuments([]);api<Document[]>('/api/documents?q='+encodeURIComponent(search),{signal:controller.signal}).then(setDocuments).catch(e=>{if(e.name!=='AbortError')setDataError(e.message)});return()=>controller.abort()},[search]);
 useEffect(()=>{const controller=new AbortController();setRows([]);setDataError('');api<{records:unknown[]}>('/api/tables/'+table+'?limit=10&offset='+offset,{signal:controller.signal}).then(r=>setRows(r.records)).catch(e=>{if(e.name!=='AbortError')setDataError(e.message)});return()=>controller.abort()},[table,offset]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth',block:'end'})},[messages,busy]);
 useEffect(()=>()=>{pending.current?.abort()},[]);
 useEffect(()=>{if(doc)dialog.current?.showModal();else dialog.current?.close()},[doc]);
 function reset(){epoch.current++;pending.current?.abort();pending.current=null;setBusy(false);setMessages([welcome]);setError('');voice.stop()}
 function changeLot(value:string){reset();setLot(value)}
 async function openDoc(id:string){const run=++docEpoch.current;try{const result=await api<Document>('/api/documents/'+encodeURIComponent(id));if(run===docEpoch.current)setDoc(result)}catch(e){setError((e as Error).message)}}
 async function ask(text:string,selectedLot=lot){
  if(!text.trim()||busy)return;
  if(selectedLot!==lot){reset();setLot(selectedLot)}
  voice.stop();const run=epoch.current;const controller=new AbortController();pending.current=controller;setBusy(true);setError('');setQuestion('');setPanel(null);
  const past=selectedLot===lot?messages:[];
  setMessages(m=>[...(selectedLot===lot?m:[welcome]),{role:'user',text}]);
  const next=[{question:text,lot:selectedLot},...history.filter(h=>h.question!==text||h.lot!==selectedLot)].slice(0,20);setHistory(next);saveStored('kwp-history',next);
  try{const response=await api<Message>('/api/chat',{method:'POST',signal:controller.signal,headers:{'Content-Type':'application/json',Authorization:'Bearer '+token},body:JSON.stringify({question:text,lot_id:selectedLot,mode,history:past.filter(m=>m.mode!=='voice').slice(-12).map(({role,text})=>({role,text:text.slice(0,12000)}))})});if(run===epoch.current)setMessages(m=>[...m,{...response,role:'assistant'}])}
  catch(e){if(run===epoch.current&&(e as Error).name!=='AbortError')setError((e as Error).message)}
  finally{if(run===epoch.current){setBusy(false);pending.current=null}}
 }
 const selected=workspace?.lots.find(l=>l.work_order===lot);
 return <div className="app-shell">
  <header className="topbar"><div className="brand"><span className="brand-mark"><Factory size={23}/></span><div><strong>광성정밀</strong><span>MANUFACTURING INTELLIGENCE</span></div></div><div className="top-actions"><span className="environment"><i/> 데모 워크스페이스</span><button className="icon-button" aria-label="설정" onClick={()=>setSettings(true)}><Settings size={19}/></button></div></header>
  <div className="mobile-nav"><button onClick={()=>setPanel(panel==='data'?null:'data')}><Database size={16}/>자료</button><span>제조 AI Agent</span><button onClick={()=>setPanel(panel==='questions'?null:'questions')}><MessageSquare size={16}/>질문</button></div>
  {panel&&<button className="scrim" aria-label="패널 닫기" onClick={()=>setPanel(null)}/>}
  <div className="workspace">
   <aside className={'left-panel side-panel '+(panel==='data'?'open':'')}><div className="panel-title"><span>자료 연결</span><span className="count">READ ONLY</span><button className="mobile-close" aria-label="자료 닫기" onClick={()=>setPanel(null)}><X size={17}/></button></div><div className="tabs"><button className={resource==='docs'?'active':''} onClick={()=>setResource('docs')}><BookOpen size={15}/>지식베이스</button><button className={resource==='tables'?'active':''} onClick={()=>setResource('tables')}><Database size={15}/>데이터허브</button></div>
   {resource==='docs'?<><label className="search"><Search size={16}/><input placeholder="문서 검색" aria-label="문서 검색" value={search} onChange={e=>setSearch(e.target.value)}/></label><p className="section-note">공정별 작업 절차 · 미승인 샘플</p><div className="document-list">{documents.map(d=><button key={d.document_id} onClick={()=>void openDoc(d.document_id)}><BookOpen size={17}/><span><small>{d.document_id}</small>{d.filename.replace(/^KWP-KB-\d+_/, '').replace('.md','')}</span><ChevronRight size={14}/></button>)}{!documents.length&&!dataError&&<p className="muted">표시할 문서가 없습니다.</p>}</div></>:<><label className="field">조회 테이블<select value={table} onChange={e=>{setTable(e.target.value);setOffset(0)}}>{workspace?.tables.map(t=><option key={t.table} value={t.table}>{t.label} · {t.count}건</option>)}</select></label><p className="section-note">원본 레코드 · {offset+1}번 행부터 표시</p><div className="table-records"><DataView data={rows}/></div><div className="pagination"><button disabled={!offset} onClick={()=>setOffset(n=>Math.max(0,n-10))}>이전</button><span>{Math.floor(offset/10)+1} 페이지</span><button disabled={offset+10>=(workspace?.tables.find(t=>t.table===table)?.count||0)} onClick={()=>setOffset(n=>n+10)}>다음</button></div></>}
   {dataError&&<p role="alert" className="error">{dataError}</p>}<div className="source-note"><ShieldCheck size={17}/><p>기록에서 시작하는 판단<small>가상 데이터 · 2026년 9월<br/>설비·금형·품질 결정은 담당자 검토</small></p></div></aside>
   <main className="conversation"><div className="conversation-header"><div><div className="eyebrow">KWANGSUNG AI AGENT <span>V2</span></div><h1>현장의 질문, 기록으로 답하다.</h1></div><button className="new-chat" onClick={reset}><Plus size={16}/>새 대화</button></div>
   <div className="context-bar"><label>작업지시 / 소재 LOT<select aria-label="작업지시 / 소재 LOT" value={lot} onChange={e=>changeLot(e.target.value)}><option value="">전체 기록</option>{workspace?.lots.map(l=><option key={l.work_order} value={l.work_order}>{l.work_order} · {l.material_lot}</option>)}</select></label><label>응답 방식<select aria-label="응답 방식" value={mode} onChange={e=>{reset();setMode(e.target.value as 'demo'|'ai')}}><option value="demo">데모 조회</option><option value="ai">AI 분석</option></select></label></div>
   {selected&&<div className="lot-strip">{selected.item_name} <span>{selected.press_id} / {selected.die_id}</span></div>}
   <div className="messages" aria-live="polite">{messages.length===1&&<div className="intro"><span className="intro-mark"><Factory size={30}/></span><p className="eyebrow">CONNECTED TO YOUR PROCESS</p><h2>입고부터 출하까지,<br/>한 대화로 이어집니다.</h2><p>공정 추적과 품질 확인에 필요한 기록을 찾아보세요.</p><div className="process-line">입고·수입검사 <span>→</span> 프레스 <span>→</span> 전착 <span>→</span> 마킹 <span>→</span> 출하검사</div><div className="kpis">{Object.entries(workspace?.dashboard||{}).map(([key,value])=><div key={key}><span>{labels[key]}</span><strong>{value}<small>건</small></strong></div>)}</div></div>}
   {messages.map((m,i)=><article key={i} className={'message '+m.role}><div className="message-label">{m.role==='user'?'나':'광성정밀 Agent'}{m.role==='assistant'&&m.mode&&<span>{m.mode==='demo'?'저장 기록 조회':m.mode==='voice'?'AI 실시간 음성':'AI 분석'}</span>}</div><p className="pre">{m.text}</p>{!!m.evidence?.length&&<EvidenceView items={m.evidence} openDoc={openDoc}/>}</article>)}{busy&&<div className="loading">기록과 근거를 확인하고 있습니다…</div>}<div ref={end}/></div>
   <div className="composer-area">{error&&<div className="error" role="alert">{error}<button aria-label="오류 닫기" onClick={()=>setError('')}><X size={14}/></button></div>}{voice.error&&<p role="alert" className="error">{voice.error}</p>}{voice.active&&<div className="voice-status"><i/>실시간 음성 연결 · {voice.state==='listening'?'듣고 있어요':voice.state==='speaking'?'말씀을 듣고 있어요':voice.state==='responding'?'답변 중':'연결 중'}<button onClick={voice.toggleMute}>{voice.muted?<MicOff size={15}/>:<Mic size={15}/>} {voice.muted?'음소거 해제':'음소거'}</button><button onClick={voice.stop}>종료</button></div>}{voice.needsPlay&&<button onClick={()=>void voice.play()}><Volume2 size={16}/>음성 재생</button>}
   <form className="composer" onSubmit={e=>{e.preventDefault();void ask(question)}}><textarea aria-label="질문 입력" placeholder="공정, 검사, 설비에 대해 질문해 보세요" value={question} maxLength={2000} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void ask(question)}}}/><div className="composer-bottom"><button type="button" className={'voice-button '+(voice.active?'active':'')} disabled={busy} onClick={()=>voice.active?voice.stop():void voice.start()}><Mic size={17}/>{voice.active?'음성 종료':'실시간 음성'}</button><button className="send" aria-label="질문 보내기" disabled={busy||!question.trim()}><ArrowUp size={21}/></button></div></form><p className="disclaimer">{mode==='demo'?'데모 조회는 정해진 DB·문서 검색입니다.':'AI 답변은 원본 근거와 함께 확인하세요.'} 샘플 자료는 제조 승인값이 아닙니다.</p></div>
   </main>
   <aside className={'right-panel side-panel '+(panel==='questions'?'open':'')}><div className="panel-title"><span>질문으로 시작하기</span><button className="mobile-close" aria-label="질문 닫기" onClick={()=>setPanel(null)}><X size={17}/></button></div><p className="section-note">자주 확인하는 제조 현장의 질문</p><div className="tabs">{Object.keys(workspace?.questions||{'생산·품질':[],'문서·규칙':[]}).map(g=><button key={g} className={group===g?'active':''} onClick={()=>setGroup(g)}>{g}</button>)}</div><div className="suggestions">{workspace?.questions[group]?.map((q,i)=><button disabled={busy} key={q} onClick={()=>void ask(q)}><span>{String(i+1).padStart(2,'0')}</span>{q}<ChevronRight size={14}/></button>)}</div><div className="history-title"><History size={16}/><strong>질의 이력</strong>{!!history.length&&<button onClick={()=>{setHistory([]);saveStored('kwp-history',[])}}>지우기</button>}</div><div className="history-list">{history.length?history.map((h,i)=><button disabled={busy} key={i} onClick={()=>void ask(h.question,h.lot)}>{h.question}<small>{h.lot||'전체 기록'} · 다시 질문</small></button>):<p className="muted">이 탭에서 물어본 질문이<br/>여기에 차곡차곡 쌓입니다.</p>}</div></aside>
  </div>
  <dialog ref={dialog} onCancel={()=>setDoc(null)} onClose={()=>setDoc(null)}><div className="dialog-head"><h2>{doc?.filename}</h2><button aria-label="문서 닫기" onClick={()=>setDoc(null)}><X size={21}/></button></div><p className="badge">{doc?.status||'미승인 샘플'}</p><p className="pre document-body">{doc?.content||doc?.text||'본문 미확인'}</p></dialog>
  {settings&&<SettingsDialog token={token} available={workspace?.ai_available||false} local={workspace?.local_ai||false} close={()=>setSettings(false)} save={value=>{reset();setToken(value);saveStored('kwp-access',value);setSettings(false)}}/>}
 </div>
}
function SettingsDialog({token,available,local,close,save}:{token:string;available:boolean;local:boolean;close:()=>void;save:(value:string)=>void}){const [value,setValue]=useState(token);const ref=useRef<HTMLDialogElement>(null);useEffect(()=>{ref.current?.showModal()},[]);return <dialog ref={ref} onCancel={close} onClose={close}><div className="dialog-head"><h2>AI 연결 설정</h2><button onClick={close} aria-label="설정 닫기"><X size={21}/></button></div><p>서버 API 키: {available?'설정됨':'미설정'}</p><p className="muted">{local?'로컬 접속은 서버 키만으로 AI를 사용할 수 있습니다.':'외부 AI 접속에는 접근 코드가 필요합니다.'} 접근 코드는 이 탭에만 저장됩니다.</p><form onSubmit={e=>{e.preventDefault();save(value)}}><label className="field">AI 접근 코드<input type="password" autoComplete="off" value={value} onChange={e=>setValue(e.target.value)}/></label><button className="primary">저장</button></form><p className="section-note">API 키는 서버에서 관리합니다. 접근 코드는 사용자 계정·업무 권한을 대신하지 않습니다.</p></dialog>}
